review 09-classes heb
ronen-e/understandinges6 pull request #23
Opened 2020-09-05 14:43 UTC by mayaliberman

Hi, 
I went over the whole section, fixed some typos. There are some issues with using "W" in the manuscript as well as in the Hebrew manuscript which is confusing to read, for example in row 1305-1315. I didn't touch it but maybe you should re-edit them to be something more comprehensible.

2020-09-09 17:26 UTC, ronen-e requested changes
can you please rebase on top of master?
Can you remove the auto format fixes and keep just the desired typo fixes ?

2020-09-11 08:17 UTC, ronen-e requested changes

2020-09-11 08:20 UTC, ronen-e commented
The problem with the "W>" is due to leanpub syntax conflicting with Github markdown.
I need to setup a way to view the files according to leanpub markdown rules.

2020-09-11 12:40 UTC, closed without merging

2020-09-11 12:41 UTC, mayaliberman commented
Updated auto fix with Prettier