Od/arrays.md heb
ronen-e/understandinges6 pull request #24
Opened 2020-09-07 23:44 UTC by odeddugma

This is 1-65 lines translation at the Arrays chapter.

2020-09-08 07:39 UTC, ronen-e requested changes

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +`Array.of()`
you need to wrap these in `ltr` spans like this:

```html
<span dir="ltr">`Array.of()`</span>
```


see what happens when you view the file on github:
https://github.com/ronen-e/understandinges6/blob/549f2eb3ca773b31ebd19fc9044e358d3b222ee2/manuscript_heb/10-Arrays.md

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +המערך הינו אובייקט ג'אווה סקריפט במהותו. עם זאת, בעוד אספקטים אחרים של ג'אווה סקריפט התפתחו במהלך הזמן, מערכים נותרו זהים עד ש-
תיקונים:
ג׳אווהסקריפט
במקום 
ג׳אווה סקריפט

היבטים
במקום
אספקטים

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +המשיכה את מגמת השיפור של המערכים על ידי הוספת פונקציונליות רבה יותר, כמו שיטות יצירה חדשות של מערכים, הפיכת כמה שיטות שימושיות לנוחות יותר לכתיב, מערכים מאופיינים.
ECMAScript 5
במקום
ECMAScript5

ECMAScript 6
במקום
ECMAScript6


נוחות יותר לכתיבה
במקום
נוחות יותר לכתיב

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +
לקונסטרקטור
במקום
לקונסטרקור

מסוכנת ומבלבלת
במקום
מסוכנת ומבולבלת

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +פשוט נעביר לה את הערכים הרצויים במערך. כך למשל בדוגמא הראשונה לעיל נוצר מערך המכיל שני מספרים. המערך שבדוגמא השניה מכיל מספר אחד והמערך האחרון מכיל סטרינג אחד. הדבר דומה לשימוש במערך מילולי ואכן ניתן
מחרוזת אחת
במקום
סטרינג אחד

מערך ליטראלי
במקום
מערך מילולי

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +אך אם נרצה להעביר את הקונסטרקטור של המערך לפונקציה אז יתכן שנרצה להתשתמש במתודה
להשתמש
במקום
להתשתמש

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +- לתשומת לב: המתודה
שימו לב
במקום
לתשומת לב

2020-09-08 07:39 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +  `Sumbol.species`
`Symbol.species`
במקום
`Sumbol.species`

2020-09-19 10:36 UTC, ronen-e commented
@odeddugma can you sync with upstream and rebase your changes on top?

2020-09-23 07:25 UTC, odeddugma commented on manuscript_heb/10-Arrays.md
> +המשיכה את מגמת השיפור של המערכים על ידי הוספת פונקציונליות רבה יותר, כמו שיטות יצירה חדשות של מערכים, הפיכת כמה שיטות שימושיות לנוחות יותר לכתיב, מערכים מאופיינים.
היה צריך לכתוב "לכתיבת". תיקנתי בהתאם.

2020-09-23 07:48 UTC, odeddugma commented
Hey, I made the changes you asked locally. I will make last proofreading and then I'll open a new pull request.


You wrote: @odeddugma can you sync with upstream and rebase your changes on top?

I'm not that famillier with github but I guess you mean that pull request, isn't it?

2020-09-23 07:48 UTC, closed without merging

2020-09-24 15:34 UTC, ronen-e commented
> Hey, I made the changes you asked locally. I will make last proofreading and then I'll open a new pull request.
> 
> You wrote: @odeddugma can you sync with upstream and rebase your changes on top?
> 
> I'm not that famillier with github but I guess you mean that pull request, isn't it?

@odeddugma  thanks for the changes.

What I mean with rebase is this:
[How do I update a GitHub forked repository?](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

Basically, the PR should contain have only your commits. For example this PR should not show commit [43feb1d](https://github.com/ronen-e/understandinges6/pull/24/commits/43feb1df57b656e243d08156f0f7a65aea2ced22)

The commits for this PR should start at your first commit which is https://github.com/ronen-e/understandinges6/pull/24/commits/bf7978aaeeff59b8de0836c968f432c3ceea627e