Od/arrays.md heb
ronen-e/understandinges6 pull request #31
Opened 2020-10-06 18:36 UTC by odeddugma

2020-10-28 05:36 UTC, ronen-e requested changes
@odeddugma 
עבודה מדהימה
תודה על התרומה
הוספתי כמה הערות

לפני מרג׳ צריך לעשות 
rebase

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +פשוט נעביר לה את הערכים הרצויים במערך. כך למשל בדוגמה הראשונה לעיל נוצר מערך המכיל שני מספרים. המערך שבדוגמה השניה מכיל מספר אחד והמערך האחרון מכיל מחרוזת אחת. הדבר דומה לשימוש במערך ליטראלי ואכן נית
לגבי המשפט:
...במערך ליטראלי ואכן ניתן להשתמש במערך מילולי...

הייתי נשאר עם המושג ״מערך ליטראלי״ בכל המשפט :
...במערך ליטראלי, ואכן ניתן להשתמש במערך ליטראלי...

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +  //use args
צריך לתרגם גם בדוגמאות קוד

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +  //use args
כנ״ל

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +```</span>
תפריד את הספאן לשורה חדשה. אחרת זה שובר את הדף

כלומר ככה:


```
</span>

במקום:
```</span>

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +```js
צריך לעשות שורה ריווח של הפרדה אחרת זה שובר

<img width="234" alt="Screen Shot 2020-10-28 at 7 28 31 AM" src="https://user-images.githubusercontent.com/10486251/97396154-2f046680-18ef-11eb-9524-21d6e0095d36.png">

במקום 

כך לדוגמה:
<span dir="ltr">
```js
let items = new Array(2);

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +`<span dir="ltr">this()</span>`
`this`
instead of 
`this()`

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +###המרת מיפוי
צריך רווח בין הסולמיות לטקסט
### המרת מיפוי
במקום
###המרת מיפוי

2020-10-28 05:36 UTC, ronen-e commented on manuscript_heb/10-Arrays.md
> +(שורה 157)
???

2020-11-07 22:17 UTC, odeddugma commented on manuscript_heb/10-Arrays.md
> +```js
לא ראיתי שיש בעיה בקוד.

2020-11-07 22:21 UTC, odeddugma commented on manuscript_heb/10-Arrays.md
> +(שורה 157)
עשיתי קצת שינוי שזה יובהר יותר. נמצא בשורה 297 בקוד שעוד מעט אשלח.

2020-11-07 22:24 UTC, odeddugma commented on manuscript_heb/10-Arrays.md
> +  //use args
בעייתי לתרגם בתוך הדוגמאות. הדירקשיין שלהן הופך ל-
LTR
ויש יותר מדי ערבוב של עברית ואנגלית וירידות שורה גם ככה.
לדעתי אם התרגום הוא ממילא של מילה אחת פשוטה (המילה
args
היא משתנה ובכל מקרה לא צריך לתרגם אותה) עדיף שלא לשחק עם זה כל כך.
אבל זו דעתי. אם אתה רוצה אחרת תגיד ואשנה.

2020-11-07 22:25 UTC, odeddugma commented on manuscript_heb/10-Arrays.md
> +  //use args
ראה תגובתי הקודמת.

2020-11-07 22:27 UTC, closed without merging

2020-11-07 22:28 UTC, odeddugma commented
נשלח פול ריקווסט חדש